-- GENERATED by dawn-theme. Do not edit.
-- Regenerate with: dawn-theme apply
--
-- Loaded by modules/decorations.lua, which reads these instead of the literals
-- it used to carry. Hyprland's rgb() form takes bare hex with no leading '#',
-- which is what matugen's `hex_stripped` produces.

return {
	activeBorder   = "rgb({{colors.primary.default.hex_stripped}})",
	inactiveBorder = "rgb({{colors.surface_container.default.hex_stripped}})",
	shadow         = "rgb({{colors.shadow.default.hex_stripped}})",
	background     = "rgb({{colors.surface.default.hex_stripped}})",
}
