-- GENERATED by dawn-theme. Do not edit.
-- Regenerate with: dawn-theme apply
--
-- Read by colors/dawn.lua, which turns these into highlight groups.
--
-- Only roles that are legible AS FOREGROUND on `surface` are exported.
-- Material You's *_container roles are background colours — under a colourful
-- scheme primary_container is a dark green, so using one as text would be
-- unreadable. matugen's base16 output is avoided for the same reason: it is
-- derived straight from the image with no contrast guarantee, and on a
-- monochrome wallpaper it collapses to black-on-black.

return {
	bg        = "{{colors.surface.default.hex}}",
	bgAlt     = "{{colors.surface_container.default.hex}}",
	bgHigh    = "{{colors.surface_container_high.default.hex}}",
	sel       = "{{colors.surface_container_highest.default.hex}}",

	fg        = "{{colors.on_surface.default.hex}}",
	fgDim     = "{{colors.on_surface_variant.default.hex}}",
	muted     = "{{colors.outline.default.hex}}",

	primary   = "{{colors.primary.default.hex}}",
	secondary = "{{colors.secondary.default.hex}}",
	tertiary  = "{{colors.tertiary.default.hex}}",

	error     = "{{colors.error.default.hex}}",
	-- Fixed, exactly as in the island: Material You has no success or warning
	-- role, and a diagnostic that changes hue stops signalling severity.
	warn      = "#e8c07d",
	ok        = "#7ec699",
}
