pragma Singleton

import QtQuick
import Quickshell
import qs.theme

/*
 * Elevation, spacing, radii and sizing for the shell — and the colour roles,
 * re-exported from Colors.qml so every `Theme.background` call site keeps
 * working.
 *
 * Colours live in Colors.qml because that file is GENERATED by the colour
 * engine. Everything else here is hand-tuned and must not be machine-written:
 * colours change with the wallpaper, 8px of padding does not.
 */
Singleton {
    id: root

    // ── Surfaces ──────────────────────────────────────────────────────────
    /// The notch itself. The reference is pure black and it matters: a true
    /// black reads as absence-of-screen rather than as a widget.
    readonly property color background: Colors.background

    /// Opacity of the notch body. 1.0 keeps the "cut out of the display"
    /// illusion. Drop to ~0.82 and enable Config.requestHyprlandBlur for a
    /// frosted-glass island instead.
    property real backgroundOpacity: 1.0

    /// Raised chips inside the island (today pill, progress troughs, buttons).
    readonly property color surface: Colors.surface
    readonly property color surfaceHigh: Colors.surfaceHigh
    readonly property color surfaceHighest: Colors.surfaceHighest

    /// Hairline that keeps the island from dissolving into a light wallpaper.
    /// Kept extremely faint — the reference has no visible edge at all.
    property bool showBorder: true
    readonly property color border: Qt.rgba(Colors.borderBase.r, Colors.borderBase.g, Colors.borderBase.b, 0.06)

    /// Specular catch along the bottom curve. Off by default: the reference
    /// notch is flat pure black, and a visible sheen is exactly what makes a
    /// shell look like a widget rather than part of the display.
    property bool showHighlight: false
    readonly property color highlight: Qt.rgba(Colors.highlightBase.r, Colors.highlightBase.g, Colors.highlightBase.b, 0.10)

    /// Costs one render layer for the island surface, which is only rebuilt
    /// while the shape is actually morphing. Turn off on a weak GPU.
    property bool shadowEnabled: true
    readonly property color shadow: Colors.shadow
    readonly property real shadowOpacity: 0.55
    readonly property int shadowRadius: 28
    readonly property int shadowOffset: 6

    // ── Text ──────────────────────────────────────────────────────────────
    readonly property color text: Colors.text
    readonly property color textSecondary: Colors.textSecondary
    readonly property color textTertiary: Colors.textTertiary
    readonly property color textQuaternary: Colors.textQuaternary

    // ── Accent ────────────────────────────────────────────────────────────
    /// The accent. Generated by dawn-theme from the wallpaper or a seed
    /// colour; nothing in the shell writes to it any more.
    ///
    /// NOT readonly, despite nothing assigning to it: `Behavior on accent`
    /// below cannot attach to a readonly property, and the crossfade is the
    /// point — the palette changes under a running shell whenever dawn-theme
    /// rewrites colors.json.
    readonly property color accentBase: Colors.accentBase
    readonly property color accentContainer: Colors.accentContainer
    readonly property color onAccent: Colors.onAccent
    property color accent: accentBase

    /// Everything accented in the shell crossfades together when the wallpaper
    /// changes, rather than the desktop switching colour on a single frame.
    /// Deliberately slower than the island's springs: this is the room
    /// changing light, not a control answering a press.
    Behavior on accent {
        enabled: Anim.accent > 0
        ColorAnimation {
            duration: Anim.accent
            easing.type: Easing.InOutQuad
        }
    }

    readonly property color positive: Colors.positive
    readonly property color warning: Colors.warning
    readonly property color danger: Colors.danger
    /// Weekend column in the calendar strip.
    readonly property color weekend: Colors.weekend

    // ── Metrics ───────────────────────────────────────────────────────────
    readonly property int spacingXs: 4
    readonly property int spacingSm: 8
    readonly property int spacing: 12
    readonly property int spacingLg: 16
    readonly property int spacingXl: 22

    /// Inner padding between the island edge and its content.
    readonly property int padH: 15
    readonly property int padV: 10

    readonly property int radiusSm: 6
    readonly property int radius: 10
    readonly property int radiusLg: 14

    /// Album art / app icon. Also the height of the media pane — the text
    /// column is sized to match the artwork, not the other way round.
    readonly property int artSize: 64
    readonly property int artRadius: 12
    readonly property int iconSize: 34
    readonly property int iconRadius: 9

    /// Thickness of progress bars and rings.
    readonly property int trackThickness: 4
    readonly property int ringThickness: 3
}
