-----------------------
---- LOOK AND FEEL ----
-----------------------

-- ── Theme colours ────────────────────────────────────────────────────────
--
-- Generated by dawn-theme into ~/.config/dawn/generated/hyprland-colors.lua,
-- from the same palette the island and the terminal use.
--
-- loadfile() rather than require(): the file is outside package.path, and a
-- fresh install has not run dawn-theme yet, so it may not exist at all. The
-- literals below are the shipped fallback for exactly that case — a desktop
-- with no window borders because a colour file was missing would be a poor
-- first impression.
local palette = {
	activeBorder   = "rgb(ffb781)",
	inactiveBorder = "rgb(261e18)",
	shadow         = "rgb(000000)",
	background     = "rgb(19120d)",
}

local chunk = loadfile(os.getenv("HOME") .. "/.config/dawn/generated/hyprland-colors.lua")
if chunk then
	local ok, generated = pcall(chunk)
	if ok and type(generated) == "table" then
		for key, value in pairs(generated) do
			palette[key] = value
		end
	end
end

local activeBorderColor = palette.activeBorder
local secondaryBorderColor = palette.inactiveBorder

-- The two ends of the active border's gradient.
--
-- `dark` is deliberately NOT palette.shadow: matugen's shadow role is
-- #000000 in every scheme, and it fills six of the eight gradient stops
-- below — so using it left three quarters of the border permanently black
-- and the theme looked like it barely applied. `background` tracks the
-- palette, so the whole gradient now moves.
local bright = palette.activeBorder
local dark = palette.background

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in          = 8,
		gaps_out         = 20,

		border_size      = 1,

		col              = {
			active_border = {
				colors = {
					dark,
					dark,
					dark,
					bright,
					dark,
					dark,
					dark,
					bright,
				},
				angle = 25,
			},
			inactive_border = secondaryBorderColor,
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing    = false,

		layout           = "dwindle",
	},

	decoration = {
		rounding           = 10,
		rounding_power     = 2,

		inactive_opacity   = 0.88,
		active_opacity     = 0.88,
		fullscreen_opacity = 0.88,

		-- inactive_opacity   = 1,
		-- active_opacity     = 1,
		-- fullscreen_opacity = 1,

		shadow             = {
			enabled      = true,
			range        = 20,
			render_power = 3,
			color        = 0xee0a0a0a,
		},

		blur               = {
			enabled  = true,
			size     = 3,
			passes   = 3,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},

	group = {
		col = {
			border_active = activeBorderColor,
		},
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})
